//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.04.10 at 10:06:40 AM CAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://synapse.ominsure.co.za/webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package uk.co.inc.argon.commons.exceptions;